{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "citus-cluster.serviceAccountName" . }}
  labels:
    {{- include "citus-cluster.labels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.clusterName }}
  labels:
    {{- include "citus-cluster.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
      # delete and deletecollection are required only for 'patronictl remove'
      - delete
      - deletecollection
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
      - patch
      - update
      # the following three privileges are necessary only when using endpoints
      - create
      - list
      - watch
      # delete and deletecollection are required only for 'patronictl remove'
      - delete
      - deletecollection
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  # The following privilege is only necessary for creation of headless service
  # for config endpoint, in order to prevent cleaning it up by the k8s master
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.clusterName }}
  labels:
    {{- include "citus-cluster.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.clusterName }}
subjects:
  - kind: ServiceAccount
    name: {{ include "citus-cluster.serviceAccountName" . }}
{{- end }}
---
{{- if and .Values.rbac.create .Values.rbac.createClusterRole }}
# ClusterRole and ClusterRoleBinding are only required if deployed not in the "default"
# namespace and you want Patroni to bypass kubernetes service
# (PATRONI_KUBERNETES_BYPASS_API_SERVICE=true)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: patroni-k8s-ep-access
  labels:
    {{- include "citus-cluster.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
    resourceNames:
      - kubernetes
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: patroni-k8s-ep-access
  labels:
    {{- include "citus-cluster.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: patroni-k8s-ep-access
subjects:
  - kind: ServiceAccount
    name: {{ include "citus-cluster.serviceAccountName" . }}
    namespace: {{ .Values.namespace }}
{{- end }}
