{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- include "citus-cluster.labels" . | nindent 4 }}
    cluster-name: {{ .Values.clusterName }}
type: Opaque
data:
  # Base64 encoded passwords
  superuser-password: {{ .Values.patroni.superuser.password | b64enc }}
  replication-password: {{ .Values.patroni.replication.password | b64enc }}
{{- end }}
