{{- if and .Values.ssl.enabled .Values.ssl.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ssl.secretName }}
  labels:
    {{- include "citus-cluster.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.ssl.caCrt }}
  ca.crt: {{ .Values.ssl.caCrt | b64enc }}
  {{- end }}
  {{- if .Values.ssl.serverCrt }}
  server.crt: {{ .Values.ssl.serverCrt | b64enc }}
  {{- end }}
  {{- if .Values.ssl.serverKey }}
  server.key: {{ .Values.ssl.serverKey | b64enc }}
  {{- end }}
{{- end }}
