apiVersion: v2
name: citus-cluster
description: A Helm chart for deploying Citus distributed PostgreSQL cluster with Patroni on Kubernetes
type: application
version: 1.5.0
appVersion: "2.10.0"
keywords:
  - citus
  - postgresql
  - patroni
  - database
  - distributed
maintainers:
  - name: Citus on K8s
